- examples/guests/build-all.sh
The target path in the build script was pointing to the top level target dir.
> Fix guest example target path

- tools/benchtool/src/backend/backend_ckbvm.rs
Although both two writings can execute the virtual machine normally, the old writing is usually used for single-step debugging.
> Use AsmMachine's Trace execution

- guest-programs/build-benchmarks.sh
CKB-VM now has full support for [RISC-V B extension](https://github.com/riscv/riscv-bitmanip), which can be beneficial for certain types of programs.
Here's the benchmark result I gathered on a Ryzen 3900x without B extension:
```
runtime/pinky/polkavm_no_gas: 5907us
runtime/pinky/polkavm_async_gas: 6242us
runtime/pinky/polkavm_sync_gas: 7447us
runtime/pinky/wasmi_stack: 248ms
runtime/pinky/wasmi_register: 159ms
runtime/pinky/wasmtime_cranelift_default: 5914us
runtime/pinky/wasmtime_cranelift_with_fuel: 8409us
runtime/pinky/wasmtime_cranelift_with_epoch: 7182us
runtime/pinky/wasmer: 13ms
runtime/pinky/pvfexecutor: 16ms
runtime/pinky/wasm3: 115ms
runtime/pinky/ckbvm_asm: 137ms
runtime/pinky/ckbvm_non_asm: 1.908s
runtime/pinky/native: 3684us
runtime/prime-sieve/polkavm_no_gas: 2050us …
```
> Enable B extension in CKB-VM's bench programs

- crates/polkavm/src/compiler.rs
`wrap_on_hostcall` has a generic parameter `S`. When calling the function this parameter is instantiated with some inference variable - `_` - Let's call it `?unknown` for now.
When calling `exec_args.set_on_hostcall` we end up equating `for<'r> <S as SandBox>::Access<'r>` with `for<'r> <?unknown as SandBox>::Access<'r>`. This currently constrains `?unknown` to `S`, even though this may not strictly be the case.
There could theoretically exist an impl like
```rust
impl<S: Sandbox> Sandbox for Wrapper<S> {
type Access<'r> = S::Access<'r>; 
}
```
with this using `wrap_on_hostcall::<Wrapper<S>>(on_hostcall);` would also compile.
Your code previously compiled due to a shortcoming of rustc when handling higher ranked regions. This will be fixed in https://github.com/rust-lang/rust/pull/119849 …
> explicitly annotate type of `wrap_on_hostcall`

- crates/polkavm/src/interpreter.rs
- crates/polkavm/src/tracer.rs
As discussed, we can do it in the interpreter instead of the tracer (we don't care too much about performance now, in the future we can for example make different variants of the interpreter loop)
> Interpreter: Trace log the current instruction

- tools/benchtool/Cargo.toml
- tools/benchtool/src/backend.rs
- tools/benchtool/src/backend/backend_wasmi.rs
- Adds `lazy.unchecked` Wasmi configuration since that is used in pallet-contracts for calls
- Enables `no-hash-maps` feature since that is used in pallet-contracts
> update Wasmi in benchtool

- Cargo.lock
- Cargo.toml
- crates/polkavm-linker/src/elf.rs
- crates/polkavm-linker/src/program_from_elf.rs
Their latest version includes more RISC-V reloc consants which we'll need anyways.
> bump `object` crate dependency

- crates/polkavm-common/src/assembler.rs
- crates/polkavm-common/src/program.rs
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_different_regs_with_offset_ok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_different_regs_without_offset_ok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_invalid_djump_to_zero_different_regs_without_offset_nok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_invalid_djump_to_zero_same_regs_without_offset_nok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_misaligned_djump_different_regs_with_offset_nok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_misaligned_djump_different_regs_without_offset_nok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_misaligned_djump_same_regs_with_offset_nok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_misaligned_djump_same_regs_without_offset_nok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_same_regs_with_offset_ok.txt
- tools/spectool/spec/src/inst_load_imm_and_jump_indirect_same_regs_without_offset_ok.txt
Adds support for `load_imm_and_jump_indirect`:
- short form: `a1 = 1234, jump [a0]`
- long form: `tmp = a0, a0 = 1234, jump [tmp]`
Short form is only accepted if the two passed registers are not the same. For the case that they are, only the long form is accepted. The outputted disassembly also follows this rule. When writing assembly, the long form will always be accepted.
> add handling of load_imm_and_jump_indirect

- ci/jobs/rustfmt.sh
- crates/polkavm/src/bit_mask.rs
- crates/polkavm/src/compiler.rs
- crates/polkavm/src/compiler/amd64.rs
- crates/polkavm/src/generic_allocator.rs
- crates/polkavm/src/sandbox.rs
- crates/polkavm/src/sandbox/generic.rs
- crates/polkavm/src/sandbox/linux.rs
- crates/polkavm/src/shm_allocator.rs
`rustfmt` [doesn't format modules declared in macros](https://github.com/rust-lang/rustfmt/issues/3253).
> Format code of modules declared in macros too

- crates/polkavm-linux-raw/src/arch_amd64_bindings.rs
- crates/polkavm-linux-raw/src/lib.rs
- crates/polkavm/src/sandbox/linux.rs
On `Linux 6.10.5-arch1-1`  I see this bubbling up and many dynamic paging tests fail as a result. In that case, just retrying fixes the test suite.
> uffd: io_uring can bubble up ERESTARTSYS

- crates/polkavm-linker/src/program_from_elf.rs
We are refactoring code so it can work with 64 bit ISA. The objective is to replace intermediate representation within the linker big enough for both 32 bit and 64 bit ISA.
> polkavm-linker: Modify RegValue so it can hold 64bit instructions

- crates/polkavm-linker/src/program_from_elf.rs
- crates/polkavm-linker/src/riscv.rs
- crates/polkavm/src/api.rs
- crates/polkavm/src/interpreter.rs
- guest-programs/test-blob/src/main.rs
The pinky benchmark should now compile in 64-bits (with the C extension and optimizations disabled).
> More 64-bit work

- capi/polkavm_guest.h
Companion: https://github.com/koute/polkadoom/pull/2
lp64 ifdef paths are untested (there might be more missing relocations in the linker).
> capi: prepare for 64bit

- .github/workflows/rust.yml
Latest CI breakdown likely related to https://github.com/actions/runner-images/issues/10636
> pin the CI runner to ubuntu-22.04

- crates/polkavm-linker/src/program_from_elf.rs
- crates/polkavm-linker/src/riscv.rs
```
polkavm-linker: Add a DecoderConfig struct
We plan to extend decoder to include Zbb instruction set, while keeping
the backward compatibility of the decoder in mind, we should add a flag
to turn on this instruction set.
Since we already have a flag for 64-bit, it will soon become ugly to keep
passing a bunch of parameters to the decoder. Let's create a DecoderConfig
to bundle the flags for the decoder.
This patch only aims to refactor code, and no functional change is intended.
Signed-off-by: Aman <aman@parity.io>
```
```
polkavm-linker: Make decode_compressed(...) a private function
...and while at it, only do compressed decoding if that is intended or
required, and do not fallback to normal decoding even if instruction
byte code suggests compressed instruction.
Signed-off-by: Aman …
```
> Minor decoder refactoring

- crates/polkavm-linker/src/riscv.rs
Updates https://github.com/riscv-non-isa/riscv-asm-manual/blob/master/riscv-asm.md#instruction-aliases to https://github.com/riscv-non-isa/riscv-asm-manual/blob/main/src/asm-manual.adoc#instruction-aliases
> chore: fix broken link in `riscv`

- crates/polkavm-linker/src/program_from_elf.rs
> fix: add missing `Reg::E3` to `from_usize` in `Reg` in `polkavm-linker`

- crates/polkavm-common/src/program.rs
- crates/polkavm-linker/src/program_from_elf.rs
- crates/polkavm/src/compiler.rs
- crates/polkavm/src/compiler/amd64.rs
- crates/polkavm/src/gas.rs
- crates/polkavm/src/interpreter.rs
And get rid orc.b emulation code from the interpreter and the recompiler.
We are making this change because orc.b is rarely used and a very complicated instruction in itself, we don't need to support or upstream such a complicated instruction to Polkavm. Therefore let's emulate the instruction within the linker.
In addition, we are adding a warn print for the linker user to make them aware that orc.b is being replaced with an instruction sequence, and any perf benefit that the user is expecting would not be visible.
> polkavm: Replace orc.b with an instruction sequence in the linker.

- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_linker.rs
We add a fuzzer for the linker, that uses RISC-V instruction encoding logic to create a sequence of valid instructions. Which then is compiled into a ELF binary and passed to the linker.
Expectation here is that the fuzzer would always generate a valid ELF binary with valid instructions, and the linker should be able to link it without any issues.
Currently the ELF binary is limited to one section (.text) and no symbols. We may want to extend that in the future.
Note: I saw some crashes that the fuzzer has reported and I am working on investigating those issues.
> fuzz: Add a linker fuzzer

- crates/polkavm-linker/src/program_from_elf.rs
- fuzz/Cargo.lock
- fuzz/fuzz_targets/fuzz_linker.rs
The fuzzer reported several valid bugs, this patch takes care of them.
Following categories of bugs were reported:
1. RegKind with a zero register.
```
[
Reg {
kind: ReverseByte,
dst: A2,
src: Zero,
},
]
```
2. apply() does not implement Rem32AndSignExtend and RemUnsigned32AndSignExtend.
```
[
RegReg {
kind: RemUnsigned32AndSignExtend,
dst: A2,
src1: T0,
src2: Zero,
},
]
```
3. apply() does not implement Div32AndSignExtend and DivUnsigned32AndSignExtend/
```
[
RegReg {
kind: DivUnsigned32AndSignExtend,
dst: T1,
src1: T2,
src2: Zero,
},
]
```
4. apply() does not implement Rem*/Div* Zero src1 register case.
```
[
RegReg {
kind: Rem64,
dst: S0,
src1: Zero,
src2: A3,
},
]
```
> polkavm-linker: Fix multiple issues reported by the fuzzer

- crates/polkavm-linker/src/dwarf.rs
- Add an extra arm when `gimli::DW_AT_high_pc` is of type `Data8`
- https://github.com/paritytech/polkavm/issues/274
> support `DW_AT_high_pc` when its data type is data8

- crates/polkavm/src/interpreter.rs
The shr operator can generate an exception if the shift is greater than the type width. However, we should be using wrapping_shr instead, which is a logical correct thing to do for an interpreter.
Bug was discovered by the interpreter fuzzer #273
> polkavm/interpreter: Use wrapping_shr instead of shr operator

- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_interpreter.rs
We add an interpreter fuzzer, that generates a valid althrough could be meaningless program, that we then run through interpreter.
Expectation here is that with grammer based fuzzing, we can find issues within the interpreter implementation.
Note, currently we do not support target jumps, conditional or unconditional.
> fuzz: Add an Interpreter fuzzer

- crates/polkavm-linker/src/program_from_elf.rs
Compiler can generate relocations that store the value into the Zero register. We should swap it with a "nop".
Fixes: #279
> polkavm-linker: Handle relocation being stored into the Zero register

- crates/polkavm-derive-impl/src/abi_support_impl/common_private.rs
- crates/polkavm-derive-impl/src/import.rs
- crates/polkavm-linker/src/program_from_elf.rs
and mark the return register properly.
We are seeing that in some debug builds trampoline subroutine is not inlined, which causes epilogue and prologue to be generated. Further corrupting the stack pointer and jumping to an incorrect address when returning from the subroutine.
We fix this by adding a return type to the trampoline subroutine and marking the return register properly, and therefore removing the "noreturn" attribute from the trampoline subroutine.
Fixes: #277
> polkavm-linker: Add a return type to the import trampoline

- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_polkavm.rs
We run both recompiler and interpreter side by side in the fuzzing harness. And then compare the results of both. This is a simple fuzzer that runs the interpreter on the input and checks if the result is the same as the recompiler.
> fuzz/fuzz_polkavm: Add correctness fuzzer for the interpreter

- .github/workflows/rust.yml
- ci/jobs/build-and-test.sh
- crates/polkavm/src/api.rs
- crates/polkavm/src/compiler/amd64.rs
- crates/polkavm/src/error.rs
- crates/polkavm/src/sandbox/generic.rs
- crates/polkavm/src/tests.rs
We have been ignoring the generic sandbox for a while now. This commit fixes the generic sandbox by implementing the updated Sandbox trait and removing the old code.
Sandbox is used to provide isolation and interface to execute compiler generated native code directly on the CPU. Generic Sandbox unlike Linux Sandbox directly runs code inside Sandbox process by modifying process memory and jumping directly to the guest code.
We implemented a bunch of interface but still some things are missing, such as gas metering, aux data access and dynamic paging.
However, now we can use the generic sandbox for testing and it is able to run 90% of our tests.
**Testing**
test result: FAILED. 573 passed; 55 failed; 0 ignored; 0 measured; 2529 filtered out; finished in 12.55s
> sandbox: Fix generic sandbox

- crates/polkavm/src/compiler/amd64.rs
- crates/polkavm/src/sandbox/generic.rs
```
sandbox: Fix generic sandbox signal handler
Generic sandbox does correctly store register file on receiving signal.
This is fine in most cases, since there is no recovery after getting a
signal, but some of our tests assert register values after receiving a
signal.
For instance, if we run out of gas and trigger SIGILL, none of the
register values will be stored in Vmctx.
```
```
sandbox: Fix gas metering for the generic sandbox
Generic sandbox uses a different base register, instead of r15 pointing
to Vmctx, it points to start of guest memory. Vmctx base address is
calculated by [r15-4096]. This increases the number of bits required for
offset when emitting instructions for gas metering.
As a result, we need more bytes for the gas metering instructions.
Following patch reworks gas …
```
> Generic sandbox gas metering and signal handler fixes

- ci/jobs/fuzz.sh
- crates/polkavm/src/interpreter.rs
- crates/polkavm/src/tests.rs
- fuzz/fuzz_targets/fuzz_polkavm.rs
Currently, the program counter always returns 0 when the last instruction is branch instruction and it evaluates to false. The correct behavior should be returning the faulting address.
This is also weird because the program counter returns correct value if the last instruction is something else.
Also, on re-compiler we do return correct faulting address.
This patch fixes interpreter behavior and makes it consistent with re-compiler.
> interpreter: Fix out-of-range execution ProgramCounter

- crates/polkavm/src/api.rs
- crates/polkavm/src/interpreter.rs
- crates/polkavm/src/tests.rs
- crates/polkavm/src/utils.rs
- tools/benchtool/Cargo.toml
This commit adds the ability to reclaim cache backed memory in the interpreter backend of the PolkaVM. It deallocates compiled code and frees up memory previously allocated by the backend. This is useful for managing memory usage during the execution of multiple programs and limiting memory footprint of the all the programs in the memory.
The obvious side effect of this change is that the cache is cleared and the next program will have to be compiled again, which may lead to slower execution for the first run after reclaiming memory.
**without reclaim logic:**
```
running 1 test
[DEBUG polkavm::api] Selected backend: 'interpreter'
[TRACE polkavm::api] Creating new module from a 32-bit program blob
[TRACE polkavm::api] Checking imports...
[TRACE polkavm::api] Checking jump table...
[TRACE …
```
> Interpreter: Allow reclaiming cache backed memory in the interpreter backend

- crates/polkavm-common/src/program.rs
- crates/polkavm-common/src/utils.rs
- crates/polkavm/src/api.rs
- crates/polkavm/src/compiler.rs
- crates/polkavm/src/interpreter.rs
- crates/polkavm/src/lib.rs
- crates/polkavm/src/tests.rs
- crates/polkavm/src/utils.rs
Add support for bounded interpreter cache and automatic cache reset when quota is exceeded.
Instead of adding a check in the instruction execution loop, we cleverly replace the first instruction of the new basic block with reset cache micro-instruction. This keeps the runner loop optimized. In addition, we make sure capacity of the interpreter cache never gets too big.
As you may notice, `max_cache_size` is not a tight upper bound, and transiently we could allocate more than `max_cache_size`. This is needed to keep the implementation optimized and complexity at bay.
Finally, we are also adding support to reset FlatMap and allocate its memory on first use.
**Testing**
```
running 1 test
[DEBUG polkavm::api] Selected backend: 'interpreter'
[TRACE polkavm::api] Creating new module from a …
```
> Bounded interpreter cache support

- ci/jobs/build-and-test.sh
- crates/polkavm-assembler/src/amd64.rs
- crates/polkavm/src/sandbox/generic.rs
```
ci: Enable all generic sandbox tests except known failing ones
While I fix the known failing tests, enable all other generic sandbox tests to
ensure that we catch any regressions early.
```
```
generic: Fix pinky dynamic paging test failure
Pinky dynamic paging test was failing because of GPF after handling a
page fault. On further investigation, it was found that the temporary
register (rcx) was not being restored properly after handling a page
fault. This causes the load address calculation to use a wrong value
in rcx, leading to a GPF.
This problem only exists on generic sandbox because we will never page
fault in between of using TMP_REG on Linux sandbox.
with this commit, we also enable the pinky dynamic paging test in CI.
```
...will post memset update as a seperate PR later.
> Enable all generic sandbox tests except for memset

- .github/workflows/rust.yml
- ci/jobs/fuzz.sh
- ci/jobs/rustfmt.sh
- crates/polkavm-common/src/program.rs
- crates/polkavm/src/interpreter.rs
- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_linker.rs
- fuzz/fuzz_targets/fuzz_polkavm.rs
- fuzz/fuzz_targets/fuzz_program_blob.rs
```
fuzz: Add fuzz test for interpreter cache size limit
We update the existing polkavm fuzzing harness to includ an optional
parameter that will set the cache size limit for the interpreter.
This will help us identify any potential issues related to bounded
cache logic.
It also found a bug where u32 multiplication could overflow when
calculating the minimum number of compiled handlers.
```
```
fuzz: Add fuzz target for ProgramBlob estimate interpreter memory usage
This commit introduces a new fuzz target, `fuzz_program_blob`, designed
to test the `ProgramBlob::estimate_interpreter_memory_usage` function.
The fuzz target generates varied inputs to ensure the function can handle
a wide range of scenarios without panicking.
Fuzzing did find an issue with integer overflow in the cache size …
```
> Fuzz interpreter memory usage API

- ci/jobs/build-and-test-linux.sh
- ci/jobs/build-and-test-macos.sh
- ci/jobs/build-and-test.sh
- crates/polkavm/src/compiler/amd64.rs
- crates/polkavm/src/sandbox/generic.rs
```
generic-sandbox: Fix signal handling on macOS
ucontext_t is different on macOS and Linux. On macOS, SIGSEGV is not
sent for page faults, instead SIGBUS is sent. This commit updates the
signal handler to check for SIGBUS on macOS.
Finally, we also fix the page fault address extraction on macOS.
Signed-off-by: Aman <aman@parity.io>
```
---
```
generic-sandbox: Fix invalid jump detection on macOS / Rosetta 2
On Rosetta 2, indirect jump to a non-canonical address doesn't trigger
a page fault (SIGBUS) right away. Instead, it jumps to the address, and then
triggers a page fault (SIGBUS) when trying to fetch the instruction.
This means that previous program counter is now lost, and now we have no
way of detecting if the guest program triggered an invalid jump or not.
We fix this program by …
```
> Fix multiple issues related to generic-sandbox when running on MacOS aarch64
